name: "action-bark"
description: "You can send push notifications to iOS via Bark"
author: "harryzcy"
inputs:
  status:
    description: Specify success or failure or cancelled.
    required: true
  on_status:
    description: |
      The status on which the notification would be sent.
      If you specify more than one, separate them by commas.
      e.g. failure, cancelled
    required: false
    default: "all"
  title:
    description: |
      Specify a custom title of the notification,
      required if status is set to custom
    required: false
    default: ""
  body:
    description: |
      Specify a custom body of the notification,
      required if status is set to custom
    required: false
    default: ""
  device_key:
    description: Specify Bark device key of your device
    required: true
  level:
    description: |
      Specify iOS notification level (default: active)
    required: false
    default: active
  badge:
    description: |
      The number displayed next to App icon
    required: false
  automatically_copy:
    description: |
      Automatically copy the content to the clipboard (must be "1" if set)
    required: false
  copy:
    description: |
      The content to be copied to the clipboard
    required: false
  sound:
    description: |
      Sound to be played, value from https://github.com/Finb/Bark/tree/master/Sounds
    required: false
  icon:
    description: |
      An url to the icon, available only on iOS 15 or later
    required: false
  group:
    description: |
      The group of the notification
    required: false
  is_archive:
    description: |
      Value must be "1". Whether or not should be archived by the app
    required: false
  url:
    description: |
      The url to be opened when the notification is clicked (defaults to GitHub run URL)
    required: false
  bark_server_url:
    description: Specify your Bark server URL
    required: true
  github_server_url:
    description: Specify your GitHub Enterprise URL
    required: false
    default: https://github.com
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: alert-octagon
  color: orange
