name: Build & Test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: latest

      - name: Install
        run: npm install

      - name: Lint
        run: |
          npm run lint
          npm run format-check

      - name: Test
        run: npm run all

      - name: Notification
        uses: ./
        if: ${{ github.actor != 'dependabot[bot]' && github.event_name != 'pull_request' }}
        with:
          status: ${{ job.status }}
          title: ${{ secrets.BARK_TITLE }}
          device_key: ${{ secrets.BARK_DEVICE_KEY }}
          level: passive
          bark_server_url: ${{ secrets.BARK_SERVER_URL }}
